# Generated by Django 5.2.17 on 2026-09-14 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="callednumber",
            name="manual_winner",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Overrides the auto-winner rule when set (True/False); unset falls back to it.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="prize_interval",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Auto-highlight a winner every N calls, starting with the first (leave blank to disable).",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
